name: Cypress Test
on: [push]

jobs:
    cypress-run:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            start: npm run test
          continue-on-error: true
        - name: Deploy report page
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.TOKEN }}
            publish_dir: ./cypress/reports/html
            user_name: 'Iunaldi'
            user_email: 'ilkerunaldi76@gmail.com'